### ISSUE TITLE
v4 compatibility issue

### ISSUE THREAD

**Issue by MichalBryxi** [Bagaar/ember-breadcrumbs#65]
When trying to use this addon in `ember-source > 4.x.x` I get:

```
breadcrumbs-item.js:9 
        
       Uncaught (in promise) ReferenceError: Ember is not defined
    at Module.callback (breadcrumbs-item.js:9:1)
    at Module.exports (loader.js:106:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
    at Module.exports (loader.js:104:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
    at Module.exports (loader.js:104:1)
    at requireModule (loader.js:27:1)
    at ModuleRegistry.get (index.js:28:1)
```

Which is caused by:

```
define("@bagaar/ember-breadcrumbs/templates/components/breadcrumbs-item", ["exports"], function (_exports) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  var _default = Ember.HTMLBars.template({
    "id": "wT5PK3s8",
    "block": "[[[42,[28,[37,1],[[28,[37,1],[[30,0,[\"breadcrumbsService\",\"containers\"]]],null]],null],null,[[[40,[[[1,\"    \"],[11,\"li\"],[16,0,[30,1,[\"itemClass\"]]],[17,2],[12],[1,\"\\n      \"],[18,3,[[30,1,[\"linkClass\"]]]],[1,\"\\n    \"],[13],[1,\"\\n\"]],[]],\"%cursor:0%\",[28,[37,3],[[30,1,[\"element\"]]],null],null]],[1]],null]],[\"container\",\"&attrs\",\"&default\"],false,[\"each\",\"-track-array\",\"in-element\",\"-in-el-null\",\"yield\"]]",
    "moduleName": "@bagaar/ember-breadcrumbs/templates/components/breadcrumbs-item.hbs",
    "isStrictMode": false
  });

  _exports.default = _default;
});
```

**Comment by bertdeblock** [comment]
You can temp work around this be specifying the following resolutions:

```json
"resolutions": {
  "@ember/render-modifiers": "^2.0.0",
  "ember-cli-htmlbars": "^6.0.0"
}
```

I'll try and make the addon compat with v4 asap.

**Comment by bertdeblock** [comment]
I've released v2 of `@bagaar/ember-breadcrumbs`, which resolves this issue.
