### ISSUE TITLE
v2 addon & ember v4 issue

### ISSUE THREAD

**Issue by MichalBryxi** [Bagaar/ember-breadcrumbs#67]
Currently getting:

```js
manager.js:632 
        
       Uncaught (in promise) Error: Invalid modifier manager compatibility specified
    at modifierCapabilities (manager.js:632:1)
    at did-insert.js:54:1
    at CustomModifierManager.getDelegateFor (manager.js:681:1)
    at CustomModifierManager.create (manager.js:697:1)
    at Object.evaluate (runtime.js:2704:1)
    at AppendOpcodes.evaluate (runtime.js:1284:1)
    at LowLevelVM.evaluateSyscall (runtime.js:5064:1)
    at LowLevelVM.evaluateInner (runtime.js:5020:1)
    at LowLevelVM.evaluateOuter (runtime.js:5012:1)
    at VM.next (runtime.js:5981:1)
```

Even with:

```
  "resolutions": {
    "@ember/render-modifiers": "^2.0.0",
    "ember-cli-htmlbars": "^6.0.0"
  }
```

**Comment by bertdeblock** [comment]
Can you reproduce this in a fresh v4.2 app?
I've updated all dependencies and all scenario's pass (3.20 LTS all the way to `embroider-optimized`).
I would be surprised if this addon is still the cause, but never know of course!

**Comment by bertdeblock** [comment]
Hi @MichalBryxi, would it be possible to confirm if you can reproduce in a fresh app?

**Comment by MichalBryxi** [comment]
@bertdeblock 👋🏾  I'm on vacation now ⛰️  Will try to give you repro / close the ticket early next week 🤓

**Comment by bertdeblock** [comment]
@MichalBryxi awesome. Enjoy!

**Comment by MichalBryxi** [comment]
Ok, checked in isolation and with:

```
    "ember-source": "~4.2.0",
    "@bagaar/ember-breadcrumbs": "^2.0.0",
```

No errors. Sorry for the noise.
